### ISSUE TITLE
Example doesn't build on Linux

### ISSUE THREAD

**Issue by zaydlang** [BindBC/bindbc-freetype#20]
Hey!

On my Linux machine, the example doesn't build. I ran `dub build` and got the following output:

```
Starting Performing "debug" build using /usr/bin/dmd for x86_64.
    Building bindbc-common 1.0.5: building configuration [noBC]
    Building bindbc-loader 1.1.5: building configuration [noBC]
    Building bindbc-freetype 1.3.0: building configuration [dynamic]
../../source/ft/colour.d(144,81): Error: cannot implicitly convert expression `"colorDodge"` of type `string` to `EnumIden`
../../source/ft/colour.d(144,96): Error: cannot implicitly convert expression `"FT_COLR_COMPOSITE_COLOR_DODGE"` of type `string` to `EnumIden`
../../source/ft/colour.d(145,81): Error: cannot implicitly convert expression `"colorBurn"` of type `string` to `EnumIden`
../../source/ft/colour.d(145,95): Error: cannot implicitly convert expression `"FT_COLR_COMPOSITE_COLOR_BURN"` of type `string` to `EnumIden`
../../source/ft/colour.d(153,81): Error: cannot implicitly convert expression `"hslColor"` of type `string` to `EnumIden`
../../source/ft/colour.d(153,94): Error: cannot implicitly convert expression `"FT_COLR_COMPOSITE_HSL_COLOR"` of type `string` to `EnumIden`
../../source/ft/colour.d(206,3): Error: alias `ft.colour.FT_PaintSweepGradient.start_angle` conflicts with variable `ft.colour.FT_PaintSweepGradient.start_angle` at ../../source/ft/colour.d(204,12)
../../source/ft/colour.d(207,3): Error: alias `ft.colour.FT_PaintSweepGradient.end_angle` conflicts with variable `ft.colour.FT_PaintSweepGradient.end_angle` at ../../source/ft/colour.d(205,12)
../../source/ft/colour.d-mixin-318(323,2): Error: undefined identifier `FT_Color_Root_Transform`
../../source/ft/colour.d-mixin-318(338,20): Error: undefined identifier `FT_Color_Root_Transform`
../../source/ft/colour.d(206,23): Error: undefined identifier `startAngle`, did you mean variable `start_angle`?
../../source/ft/colour.d(207,21): Error: undefined identifier `endAngle`, did you mean variable `end_angle`?
../../source/ft/colour.d(277,21): Error: undefined identifier `FT_Composite_Mode`
Error /usr/bin/dmd failed with exit code 1.
```

Did I do something incorrect here? Any thoughts are welcome :)

EDIT: formatting

**Comment by ichordev** [comment]
Ah, there’s a typo in all of the aliases for that enum declaration. Let me go fix that.

**Comment by ichordev** [comment]
Should be fixed in 1.3.1

**Comment by zaydlang** [comment]
The turnaround time is insane. Thanks! Still getting errors, though not as many:

```
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
  Up-to-date bindbc-common 1.0.5: target for configuration [noBC] is up to date.
  Up-to-date bindbc-loader 1.1.5: target for configuration [noBC] is up to date.
    Building bindbc-freetype 1.3.1: building configuration [dynamic]
../../source/ft/colour.d(206,3): Error: alias `ft.colour.FT_PaintSweepGradient.start_angle` conflicts with variable `ft.colour.FT_PaintSweepGradient.start_angle` at ../../source/ft/colour.d(204,12)
../../source/ft/colour.d(207,3): Error: alias `ft.colour.FT_PaintSweepGradient.end_angle` conflicts with variable `ft.colour.FT_PaintSweepGradient.end_angle` at ../../source/ft/colour.d(205,12)
../../source/ft/colour.d-mixin-318(323,2): Error: undefined identifier `FT_Color_Root_Transform`
../../source/ft/colour.d-mixin-318(338,20): Error: undefined identifier `FT_Color_Root_Transform`
../../source/ft/colour.d(206,23): Error: undefined identifier `startAngle`, did you mean variable `start_angle`?
../../source/ft/colour.d(207,21): Error: undefined identifier `endAngle`, did you mean variable `end_angle`?
Error /usr/bin/dmd failed with exit code 1.
```

**Comment by ichordev** [comment]
> The turnaround time is insane. Thanks!

Not a problem!

> Still getting errors, though not as many:
> 
> ```
>     Starting Performing "debug" build using /usr/bin/dmd for x86_64.
>   Up-to-date bindbc-common 1.0.5: target for configuration [noBC] is up to date.
>   Up-to-date bindbc-loader 1.1.5: target for configuration [noBC] is up to date.
>     Building bindbc-freetype 1.3.1: building configuration [dynamic]
> ../../source/ft/colour.d(206,3): Error: alias `ft.colour.FT_PaintSweepGradient.start_angle` conflicts with variable `ft.colour.FT_PaintSweepGradient.start_angle` at ../../source/ft/colour.d(204,12)
> ../../source/ft/colour.d(207,3): Error: alias `ft.colour.FT_PaintSweepGradient.end_angle` conflicts with variable `ft.colour.FT_PaintSweepGradient.end_angle` at ../../source/ft/colour.d(205,12)
> ../../source/ft/colour.d-mixin-318(323,2): Error: undefined identifier `FT_Color_Root_Transform`
> ../../source/ft/colour.d-mixin-318(338,20): Error: undefined identifier `FT_Color_Root_Transform`
> ../../source/ft/colour.d(206,23): Error: undefined identifier `startAngle`, did you mean variable `start_angle`?
> ../../source/ft/colour.d(207,21): Error: undefined identifier `endAngle`, did you mean variable `end_angle`?
> Error /usr/bin/dmd failed with exit code 1.
> ```

I have released 1.3.2, which should address those. :) If not, keep 'em coming!

**Comment by zaydlang** [comment]
Nice, it compiles and works now! Thanks!
